# Build documentation
name: Documentation Build

on: [push, pull_request, workflow_dispatch]

jobs:
  docs_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install ansys-mapdl-core
        run: |
          python setup.py sdist
          pip install dist/pyansys*.tar.gz
  
      - name: Build Documentation
        run: |
          pip install -r docs/requirements.txt
          make -C docs html
          touch docs/build/html/.nojekyll
          echo "sphinxdocs.pyansys.com" > docs/build/html/CNAME
  
      - name: Upload Documentation
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Documentation
          path: docs/build/html
          retention-days: 7

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true